# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_DIV64_KUNIT_TEST)    += div64_kunit.o
obj-$(CONFIG_INT_POW_KUNIT_TEST)  += int_pow_kunit.o
obj-$(CONFIG_MULDIV64_KUNIT_TEST) += mul_u64_u64_div_u64_kunit.o
obj-$(CONFIG_RATIONAL_KUNIT_TEST) += rational_kunit.o
